apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  selector:
    name: apigateway
    tier: backend
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apigateway
spec:
  replicas: 2 # number of instances
  template:
    metadata:
      labels:
        name: apigateway
        tier: backend
        type: deployment
    spec:
      containers:
      - name: apigateway
        image: "gcr.io/lexv-159619/apigateway:v0.0.2"
        env:
          - name: PORT
            value: "4000"
          - name: NODE_ENV
            value: "production"
          - name: AUTH0_SECRET
            valueFrom:
              secretKeyRef:
                name: apigateway-secret
                key: auth0_secret
          - name: AUTH0_AUDIENCE
            valueFrom:
              secretKeyRef:
                name: apigateway-secret
                key: auth0_audience
        ports:
        - name: http
          containerPort: 4000
