apiVersion: v1
kind: Service
metadata:
  labels:
    name: queueclient
  name: queueclient
spec:
  selector:
    name: queueclient
    tier: backend
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: queueclient
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: queueclient
        tier: backend
        type: deployment
    spec:
      containers:
      - name: queueclient
        image: "gcr.io/lexv-159619/queueclient:v0.0.8"
        command: [
          "./queue-client",
          "-redis=redis://redis:6379",
          "-ns=work",
          "-listen=0.0.0.0:5040"]
        ports:
        - name: http
          containerPort: 5040
