apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: queue-manager
spec:
  replicas: 1 # number of instances
  template:
    metadata:
      labels:
        name: queue-manager
        tier: infra
        type: deployment
    spec:
      containers:
      - name: queue-manager
        image: "gcr.io/lexv-159619/queue-manager:v0.1.0"
