apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis
    role: master
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis
    role: master
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: redis
    role: master
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: redis
        tier: backend
        role: master
        type: deployment
    spec:
      containers:
      - name: redis
        image: redis
        env:
        - name: MASTER
          value: "true"
        ports:
        - name: redis-server
          containerPort: 6379
          hostPort: 6379
