apiVersion: v1
kind: Service
metadata:
  name: transriber
spec:
  selector:
    name: transriber
    tier: backend
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: transriber
spec:
  replicas: 5 # number of instances
  template:
    metadata:
      labels:
        name: transriber
        tier: backend
        type: deployment
    spec:
      containers:
      - name: transriber
        image: gcr.io/<OUR-PROJECT-ID>/app
        env:
        - name: PORT
          value: ""
        ports:
        - name: http
          containerPort: 4000
