apiVersion: v1
kind: Service
metadata:
  labels:
    name: transcriber
  name: transcriber
spec:
  selector:
    name: transriber
    tier: backend
  ports:
    - port: 80
      targetPort: transcriberhttp
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: transcriber
spec:
  replicas: 1 # number of instances
  template:
    metadata:
      labels:
        name: transcriber
        tier: backend
        type: deployment
    spec:
      containers:
      - name: transcriber
        image: "gcr.io/lexv-159619/transcriber:v0.0.6"
        env:
        - name: ENVIRONMENT
          value: "production"
        ports:
        - name: transcriberhttp
          containerPort: 5000
