apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx-upstreams: |
    upstream apigateway {
        server apigateway;
    }
---
apiVersion: v1
kind: Service
metadata:
  name: webclient
spec:
  selector:
    app: webclient
    tier: frontend
  ports:
    - protocol: "TCP"
      port: 80 # open to the web
      targetPort: 80
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webclient
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webclient
        tier: frontend
        type: deployment
    spec:
      containers:
        - name: nginx
          image: "gcr.io/lexv-159619/webclient:v0.0.7"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/upstreams
              name: nginx-upstreams
      volumes:
      - name: nginx-upstreams
        configMap:
          name: nginx-config
          items:
          - key: nginx-upstreams
            path: upstreams.conf
