apiVersion: v1
kind: Service
metadata:
  name: searchengine
spec:
  selector:
    name: searchengine
    tier: backend
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: searchengine
spec:
  replicas: 3 # number of instances
  template:
    metadata:
      labels:
        name: searchengine
        tier: backend
        type: controller
    spec:
      containers:
      - name: searchengine
        image: gcr.io/<OUR-PROJECT-ID>/app
        ports:
        - name: http
          containerPort: 3000
