export const SEARCHED_VIDEOS = 'SEARCHED_VIDEOS'
export const RECEIVED_VIDEOS = 'RECEIVED_VIDEOS'
export const CLEARED_VIDEOS_RESULTS = 'CLEARED_VIDEOS_RESULTS'

export const SEARCHED_MARKERS = 'SEARCHED_MARKERS'
export const RECEIVED_MARKERS = 'RECEIVED_MARKERS'
export const CLEARED_MARKERS_RESULTS = 'CLEARED_MARKERS_RESULTS'

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST'
export const AUTHENTIFICATE_USER_REQUEST = 'AUTHENTIFICATE_USER_REQUEST'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'
export const LOGOUT_USER = 'LOGOUT_USER'

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
