export const SEARCHED_VIDEOS = 'SEARCHED_VIDEOS'
export const RECEIVED_VIDEOS = 'RECEIVED_VIDEOS'
export const CLEARED_VIDEOS_RESULTS = 'CLEARED_VIDEOS_RESULTS'

export const SEARCHED_MARKERS = 'SEARCHED_MARKERS'
export const RECEIVED_MARKERS = 'RECEIVED_MARKERS'
export const CLEARED_MARKERS_RESULTS = 'CLEARED_MARKERS_RESULTS'
